version: '3.8'

services:
  # FUSAF Application
  fusaf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fusaf-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://fusaf_user:${MYSQL_PASSWORD}@fusaf-db:3306/fusaf_production
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      - fusaf-db
    networks:
      - fusaf-network
    ports:
      - "3000:3000"
    volumes:
      - app-uploads:/app/public/uploads

  # MySQL Database
  fusaf-db:
    image: mysql:8.0
    container_name: fusaf-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: fusaf_production
      MYSQL_USER: fusaf_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/backups:/backups
    networks:
      - fusaf-network
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  # Nginx Reverse Proxy
  fusaf-nginx:
    image: nginx:alpine
    container_name: fusaf-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - app-uploads:/var/www/uploads
    depends_on:
      - fusaf-app
    networks:
      - fusaf-network

volumes:
  mysql-data:
    driver: local
  app-uploads:
    driver: local

networks:
  fusaf-network:
    driver: bridge
