[build]
  command = "npm install --legacy-peer-deps cross-env && npm run build:netlify"
  publish = ".next"

[build.environment]
  NEXT_RUNTIME = "nodejs18.x"
  SKIP_TYPE_CHECK = "true"
  DISABLE_ESLINT = "true"
  CI = "false"
  TYPESCRIPT = "false"
  ESLint = "false"
  # Додаткові змінні для відключення TypeScript
  NEXT_SKIP_TYPE_CHECK = "true"
  SKIP_TYPESCRIPT = "true"
  DISABLE_TYPE_CHECK = "true"
  NO_TYPESCRIPT = "true"
  FORCE_SKIP_TYPE_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  TYPESCRIPT_IGNORE_BUILD_ERRORS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Підтримка Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Headers для безпеки
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache налаштування
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
